

services:
  assistant:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env
    depends_on:
      - postgres
    networks:
      - postgres 

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
    - "5432:5432"
    - "8080:8080"
    volumes:
      - postgres_data:/var/lib/postgresql/data 
      - ./src/api/database/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks: 
    - postgres 
    restart: unless-stopped



networks:
  postgres:
    driver: bridge

volumes:
 postgres_data:



